# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe43f48c516280f750ff568f17bda6453a575c8737310193cf699a0dc4aab856f7eb120bf9aef5cfba4d3f746daaa8280cd30c995fda2dd756b36a92a8fb2d45

test:
  secret_key_base: 4cba67855b4bef1aae55de28d63a4bba68e308ef93d0b04dcc9c38fee36f2b77b90b05a200a919c3ef03210f5d2ad19b529ac754064db661a07c4cd3adbc2f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
